-- 00168_instituto_seed.sql
-- ============================================================================
-- SEED do Instituto Estúdio Mais — INTENCIONALMENTE EM BRANCO
-- ============================================================================
--
-- Esta migration NÃO popula instituto_metrics nem instituto_depoimentos.
--
-- Decisão de produto: enquanto as 2 tabelas estiverem vazias, as telas Clube
-- e Instituto escondem automaticamente as seções de métricas e depoimentos.
-- Cliente vê uma versão limpa sem números chutados.
--
-- Quando o time do Instituto tiver os 4 números oficiais + 3-5 alunas reais,
-- popular MANUALMENTE via Supabase Studio ou rodar uma migration nova
-- (sugestão: 00169_instituto_real_data.sql).
--
-- Estrutura dos campos pra popular manualmente:
--
-- ============================================================================
-- 1. instituto_metrics — UPDATE dos 4 metrics existentes (já criados em 00166)
-- ============================================================================
--
-- UPDATE public.instituto_metrics SET current_value = <N> WHERE metric_key = 'total_alunas_formadas';
-- UPDATE public.instituto_metrics SET current_value = <CENTAVOS> WHERE metric_key = 'total_doado_centavos';
-- UPDATE public.instituto_metrics SET current_value = <N> WHERE metric_key = 'current_turma_size';
-- UPDATE public.instituto_metrics SET current_value = EXTRACT(EPOCH FROM '<YYYY-MM-DD>'::timestamptz)::numeric WHERE metric_key = 'next_turma_starts_at_ts';
--
-- ============================================================================
-- 2. instituto_depoimentos — INSERT por aluna real
-- ============================================================================
--
-- INSERT INTO public.instituto_depoimentos
--   (full_name, age, city, professional_area, graduation_year, current_status,
--    short_quote, full_story, photo_url, video_url, is_published, display_order)
-- VALUES
--   ('<Nome>', <idade>, '<cidade>', '<esteticista|biomedica|nutricionista>',
--    <ano>, '<status hoje>',
--    '<frase de impacto curta>',
--    '<história completa 300-400 palavras>',
--    '<URL da foto ou NULL>',
--    '<URL do vídeo ou NULL>',
--    true, <ordem 1..5>);
--
-- ============================================================================
-- 3. clube_stock_visibility — popular mensalmente por unidade
-- ============================================================================
--
-- INSERT INTO public.clube_stock_visibility
--   (unit_id, service_id, year_month, monthly_capacity, visibility_label, is_active, display_order)
-- SELECT
--   '<unit_id>'::uuid,
--   id,                            -- service_id de services pelo nome
--   to_char(now(), 'YYYY-MM'),
--   <capacidade>,
--   '<rótulo customizado opcional>',
--   true,
--   <ordem>
-- FROM public.services WHERE name ILIKE '<nome do procedimento>';
--
-- ============================================================================
--
-- NADA EXECUTÁVEL ABAIXO. Migration é no-op por design.

SELECT 1;
